---
- name: Install Apache Web Server on Ubuntu EC2 Hosts
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Ensure apache2 is running and enabled
      service:
        name: apache2
        state: started
        enabled: true
